### PR TITLE
- Fix for MacOSX Mojave

### PR DESCRIPTION
**Pull request by Spilly**
- This fix works for Mojave

### CODE REVIEW

**Comment by BrOrlandi** [comment]
This should fix #2 hope it gets a new release soon! 😉

**Comment by BrOrlandi** [comment]
@gabriellorin Do you have some time to check this PR?

Thanks!

**Comment by theophanemayaud** [comment]
This would be awesome ! Bring it back to mojave 😍

**Comment by gabriellorin** [comment]
Sorry for the delay, and thanks for the fix!!! Will check it tonight! 😊

**Pull request merged**
